version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=tasks-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5436:5432

  app:
    build: ./
    command: ./req_3rd-party_services
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data: