version: '3.8'
services:
  db:
    restart: always
    image: postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - 5436:5432

  app:  
    build: ./
    command: ./req_3rd-party_services
    ports:
      - 8080:8080
    depends_on:
      - db