port: "8000"

db:
    username: "postgres"
    host: "localhost"
    port: "5436"
    dbname: "postgres"
    sslmode: "disable"
    password: "qwerty"

redis:
    addr: "localhost:6379"
    password: "qwerty"
    db: 0